import React, { useState, useRef } from 'react';
import { 
  BookOpen, 
  PenSquare, 
  Heart, 
  MessageSquare, 
  Share2, 
  Calendar, 
  Clock, 
  User, 
  Tag, 
  Search, 
  Check, 
  ChevronLeft, 
  Sparkles, 
  Globe, 
  Send, 
  X, 
  Eye, 
  Code,
  Layers,
  CheckCircle2,
  HardDrive,
  FileText,
  Music,
  Video,
  Image as ImageIcon,
  Download,
  ExternalLink,
  Camera,
  Smartphone
} from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { BlogPost, BlogMediaItem } from '../types';
import { BlogMediaUpload } from './BlogMediaUpload';
import { BlogAiSuggestionsPanel } from './BlogAiSuggestionsPanel';
import { NativeCameraCaptureModal } from './NativeCameraCaptureModal';
import { UniversalAiSuggestionBox } from './UniversalAiSuggestionBox';

export const BlogView: React.FC = () => {
  const { 
    blogPosts, 
    activeBlogPost, 
    setActiveBlogPost, 
    publishBlogPost, 
    likeBlogPost, 
    addBlogComment,
    autoArticleStatus,
    triggerAutoArticleGeneration,
    fetchAutoArticleStatus,
    showNotification
  } = useStore();

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [isWritingModalOpen, setIsWritingModalOpen] = useState(false);
  const [isCoverCameraOpen, setIsCoverCameraOpen] = useState(false);
  const [isTriggeringAutoRun, setIsTriggeringAutoRun] = useState(false);
  const coverCameraInputRef = useRef<HTMLInputElement>(null);
  const [copiedToast, setCopiedToast] = useState(false);
  const [commentInput, setCommentInput] = useState('');
  const [commentAuthor, setCommentAuthor] = useState('Curious Reader');
  const [showSeoJsonLd, setShowSeoJsonLd] = useState(false);

  // New Article Form state
  const [newTitle, setNewTitle] = useState('');
  const [newSubtitle, setNewSubtitle] = useState('');
  const [newAuthor, setNewAuthor] = useState('Johnny Blue');
  const [newAuthorRole, setNewAuthorRole] = useState<'Author' | 'Reader' | 'Visitor' | 'Literary Scholar' | 'Books Critic'>('Author');
  const [newCategory, setNewCategory] = useState('10 Dimensions & Hardware');
  const [newCoverImage, setNewCoverImage] = useState('https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1200');
  const [newTags, setNewTags] = useState('Literature, 10 Dimensions, Publishing');
  const [newContent, setNewContent] = useState('');
  const [mediaItems, setMediaItems] = useState<BlogMediaItem[]>([]);
  const [showAiAssistant, setShowAiAssistant] = useState(true);

  // Categories with Auto-Articles filter
  const categories = [
    { id: 'all', label: 'All Articles' },
    { id: 'auto_generated', label: '✦ 2-Hour Global AI Editions' },
    { id: '10 Dimensions & Hardware', label: '10 Dimensions & Hardware' },
    { id: 'Craft & Writing', label: 'Craft & Writing' },
    { id: 'Publishing Industry', label: 'Publishing & Royalties' },
    { id: 'Philosophy & Literature', label: 'Philosophy & Literature' },
    { id: 'Books & Global Research', label: 'Books & Research' },
    { id: 'EdTech & Learning', label: 'EdTech & Learning' },
    { id: 'News & Magazines', label: 'News & Magazines' }
  ];

  const handleTriggerAutoArticle = async () => {
    setIsTriggeringAutoRun(true);
    showNotification('⚡ Triggering 2-Hour Global Gemini AI Edition generation...');
    try {
      const success = await triggerAutoArticleGeneration();
      if (success) {
        showNotification('✓ New Global Gemini AI Article published successfully with self-generated featured image!');
        await fetchAutoArticleStatus();
      } else {
        showNotification('Autonomous article generated and added to Knowledge Centa feed.');
      }
    } catch (err) {
      showNotification('Error triggering 2-hour autonomous generation.');
    } finally {
      setIsTriggeringAutoRun(false);
    }
  };

  const filteredPosts = blogPosts.filter((post) => {
    let matchesCat = true;
    if (selectedCategory === 'auto_generated') {
      matchesCat = !!post.isAutoGenerated;
    } else if (selectedCategory !== 'all') {
      matchesCat = post.category === selectedCategory;
    }
    const query = searchQuery.toLowerCase();
    const matchesSearch = 
      !searchQuery ||
      post.title.toLowerCase().includes(query) ||
      post.author.toLowerCase().includes(query) ||
      (post.tags && post.tags.some(t => t.toLowerCase().includes(query))) ||
      (post.seoKeywords && post.seoKeywords.some(k => k.toLowerCase().includes(query))) ||
      post.excerpt.toLowerCase().includes(query);
    return matchesCat && matchesSearch;
  });

  const handleShare = (post: BlogPost) => {
    const url = `${window.location.origin}/#blog?slug=${post.slug}`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(url);
    }
    setCopiedToast(true);
    setTimeout(() => setCopiedToast(false), 2500);
  };

  const handleShareWhatsApp = (post: BlogPost) => {
    const url = `${window.location.origin}/#blog?slug=${post.slug}`;
    const text = encodeURIComponent(`Check out "${post.title}" on Johnnyblue1 Books Stores & Knowledge Centa: ${url}`);
    window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank');
  };

  const handleCreateArticle = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim() || !newContent.trim()) return;

    const parsedTags = newTags
      .split(',')
      .map(t => t.trim())
      .filter(Boolean);

    await publishBlogPost({
      title: newTitle.trim(),
      subtitle: newSubtitle.trim() || 'An insightful exploration on literature and the 10 dimensions of publishing.',
      author: newAuthor.trim(),
      authorRole: newAuthorRole,
      authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
      category: newCategory,
      excerpt: newContent.slice(0, 160) + '...',
      content: newContent,
      coverImage: newCoverImage || 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=1200',
      readTimeMinutes: Math.max(3, Math.ceil(newContent.split(' ').length / 200)),
      tags: parsedTags.length > 0 ? parsedTags : ['Publishing', 'Books'],
      featuredBookId: 'book-1',
      media: mediaItems
    });

    setIsWritingModalOpen(false);
    setNewTitle('');
    setNewSubtitle('');
    setNewContent('');
    setMediaItems([]);
  };

  const handleAddComment = (postId: string) => {
    if (!commentInput.trim()) return;
    addBlogComment(postId, commentInput, commentAuthor);
    setCommentInput('');
  };

  // Schema.org Article Structured Data for Google & AI bots
  const currentPostJsonLd = activeBlogPost ? {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": activeBlogPost.title,
    "description": activeBlogPost.subtitle || activeBlogPost.excerpt,
    "image": [activeBlogPost.coverImage],
    "datePublished": activeBlogPost.publishedAt,
    "author": [{
      "@type": "Person",
      "name": activeBlogPost.author,
      "jobTitle": activeBlogPost.authorRole
    }],
    "publisher": {
      "@type": "Organization",
      "name": "Johnnyblue1 Books Stores & Knowledge Centa",
      "logo": {
        "@type": "ImageObject",
        "url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500"
      }
    },
    "keywords": activeBlogPost.tags.join(', ')
  } : null;

  return (
    <div className="bg-[#fcfbf9] text-slate-900 min-h-screen py-8 px-4 sm:px-6">
      <div className="max-w-5xl mx-auto space-y-8">
        {/* Header Hero Section */}
        <div className="bg-[#131921] text-white p-6 sm:p-8 rounded-2xl shadow-md border border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="bg-amber-400 text-slate-950 font-bold px-2.5 py-0.5 rounded text-xs uppercase">
                Knowledge Centa Blog & Articles
              </span>
              <span className="text-emerald-400 text-xs font-semibold flex items-center gap-1">
                <Globe className="w-3.5 h-3.5" />
                Google & AI Search Engine Indexed
              </span>
            </div>
            <h1 className="text-2xl sm:text-4xl font-extrabold font-serif">
              Literary Insights & 10-Dimension Publishing
            </h1>
            <p className="text-xs sm:text-sm text-slate-300 max-w-2xl leading-relaxed">
              Open writing platform for authors, scholars, reviewers, and readers. Every article is rendered with Schema.org microdata, canonical tags, and auto-indexed for Google, Perplexity, and AI search engines.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 shrink-0">
            <button
              id="trigger-auto-article-hero-btn"
              onClick={handleTriggerAutoArticle}
              disabled={isTriggeringAutoRun}
              className="px-4 py-3 bg-stone-800 hover:bg-stone-700 border border-amber-500/40 text-amber-300 font-bold text-xs rounded-xl shadow transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-60"
              title="Autonomous engine publishes every 2 hours; click to trigger immediately"
            >
              <Sparkles className={`w-4 h-4 text-amber-400 ${isTriggeringAutoRun ? 'animate-spin' : ''}`} />
              <span>{isTriggeringAutoRun ? 'Publishing AI Edition...' : '⚡ Trigger 2-Hr AI Edition'}</span>
            </button>

            <button
              id="write-article-hero-btn"
              onClick={() => setIsWritingModalOpen(true)}
              className="px-5 py-3 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-500 hover:to-amber-600 text-slate-950 font-black text-xs sm:text-sm rounded-xl shadow-lg transition flex items-center justify-center gap-2 cursor-pointer shrink-0"
            >
              <PenSquare className="w-4 h-4" />
              <span>Write & Publish Article</span>
            </button>
          </div>
        </div>

        {/* 2-Hour Automated Global AI Publishing Status Banner */}
        <div className="bg-gradient-to-r from-amber-950/40 via-stone-900 to-slate-900 border border-amber-500/30 rounded-2xl p-4 sm:p-5 text-white shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-start gap-3.5">
            <div className="p-2.5 rounded-xl bg-amber-500/20 text-amber-400 border border-amber-500/30 shrink-0 mt-0.5">
              <Sparkles className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <div className="flex flex-wrap items-center gap-2">
                <span className="flex items-center gap-1.5 text-xs font-bold text-amber-400">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
                  <span>2-Hour Automated Global Gemini AI Engine</span>
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-stone-800 text-stone-300 border border-stone-700">
                  Active Dispatch Loop (120 min)
                </span>
              </div>
              <p className="text-xs text-stone-300 max-w-2xl leading-relaxed">
                Automatically researches and publishes in-depth long-form articles every 2 hours across rotating global domains: <em>Books & Publishing, EduTech, Scientific Research, Cognition, and News/Magazines</em> with self-curated featured visual photography and structured JSON-LD SEO schema.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3 w-full md:w-auto justify-between md:justify-end shrink-0 pt-2 md:pt-0 border-t md:border-t-0 border-stone-800">
            <div className="text-right hidden sm:block">
              <span className="text-[10px] text-stone-400 uppercase tracking-wider block">Global Dispatch</span>
              <span className="text-xs font-bold text-amber-400 font-mono">
                {blogPosts.filter(p => p.isAutoGenerated).length} AI Editions Live
              </span>
            </div>
            <button
              onClick={handleTriggerAutoArticle}
              disabled={isTriggeringAutoRun}
              className="px-3.5 py-2 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-stone-950 font-bold text-xs rounded-xl shadow transition flex items-center gap-1.5 cursor-pointer disabled:opacity-60"
            >
              <Sparkles className={`w-3.5 h-3.5 ${isTriggeringAutoRun ? 'animate-spin' : ''}`} />
              <span>{isTriggeringAutoRun ? 'Generating Article...' : 'Run Engine Now'}</span>
            </button>
          </div>
        </div>

        {/* Breadcrumb / Back button if reading specific post */}
        {activeBlogPost ? (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <button
                onClick={() => setActiveBlogPost(null)}
                className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-slate-950 transition cursor-pointer"
              >
                <ChevronLeft className="w-4 h-4" />
                <span>Back to All Articles</span>
              </button>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => setShowSeoJsonLd(!showSeoJsonLd)}
                  className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-xs rounded-lg border border-slate-300 transition flex items-center gap-1.5 cursor-pointer"
                >
                  <Code className="w-3.5 h-3.5 text-amber-600" />
                  <span>{showSeoJsonLd ? 'Hide SEO Schema' : 'Inspect Google JSON-LD'}</span>
                </button>

                <button
                  onClick={() => handleShareWhatsApp(activeBlogPost)}
                  className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs rounded-lg shadow transition flex items-center gap-1.5 cursor-pointer"
                  title="Share on WhatsApp"
                >
                  <span>WhatsApp</span>
                </button>

                <button
                  onClick={() => handleShare(activeBlogPost)}
                  className="px-3 py-1.5 bg-amber-400 hover:bg-amber-500 text-slate-950 font-bold text-xs rounded-lg shadow transition flex items-center gap-1.5 cursor-pointer"
                  title="Copy link"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  <span>Share</span>
                </button>
              </div>
            </div>

            {/* Google / AI SEO Structured Data Inspector */}
            {showSeoJsonLd && currentPostJsonLd && (
              <div className="bg-slate-900 text-emerald-400 p-4 rounded-xl font-mono text-[11px] overflow-x-auto border border-slate-700 shadow-inner space-y-2">
                <div className="flex items-center justify-between text-slate-300 pb-2 border-b border-slate-800">
                  <span className="font-bold flex items-center gap-1 text-xs text-white">
                    <Globe className="w-4 h-4 text-emerald-400" />
                    Schema.org Article Microdata (Parsed by Googlebot & AI Crawlers)
                  </span>
                  <span className="text-[10px] text-emerald-400 bg-emerald-950 px-2 py-0.5 rounded border border-emerald-500/30">
                    Valid Schema
                  </span>
                </div>
                <pre>{JSON.stringify(currentPostJsonLd, null, 2)}</pre>
              </div>
            )}

            {/* Main Article Container */}
            <article className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="relative h-64 sm:h-96 w-full">
                <img
                  src={activeBlogPost.coverImage}
                  alt={activeBlogPost.title}
                  className="w-full h-full object-cover object-center"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent" />
                <div className="absolute bottom-6 left-6 right-6 text-white space-y-2">
                  <span className="bg-amber-400 text-slate-950 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider">
                    {activeBlogPost.category}
                  </span>
                  <h1 className="text-xl sm:text-3xl font-serif font-black drop-shadow-md leading-tight">
                    {activeBlogPost.title}
                  </h1>
                  <p className="text-xs sm:text-sm text-slate-200 font-medium line-clamp-2">
                    {activeBlogPost.subtitle}
                  </p>
                </div>
              </div>

              {/* Author & Metadata Bar */}
              <div className="px-6 py-4 border-b border-slate-100 flex flex-wrap items-center justify-between gap-4 bg-slate-50/70">
                <div className="flex items-center gap-3">
                  <img
                    src={activeBlogPost.authorAvatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100'}
                    alt={activeBlogPost.author}
                    className="w-10 h-10 rounded-full border border-amber-400 object-cover"
                  />
                  <div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-xs font-bold text-slate-900 block">{activeBlogPost.author}</span>
                      {activeBlogPost.isAutoGenerated && (
                        <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-amber-500/20 text-amber-900 border border-amber-500/30">
                          2-Hour AI Dispatch #{activeBlogPost.editionCycle}
                        </span>
                      )}
                    </div>
                    <span className="text-[11px] text-slate-500">{activeBlogPost.authorRole}</span>
                  </div>
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-500">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5" />
                    {new Date(activeBlogPost.publishedAt).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />
                    {activeBlogPost.readTimeMinutes} min read
                  </span>
                  <button
                    onClick={() => likeBlogPost(activeBlogPost.id)}
                    className="flex items-center gap-1 font-bold text-rose-600 hover:scale-105 transition cursor-pointer"
                  >
                    <Heart className="w-4 h-4 fill-rose-500" />
                    <span>{activeBlogPost.likesCount}</span>
                  </button>
                </div>
              </div>

              {/* 2-Hour Autonomous Global Edition Metadata Card */}
              {activeBlogPost.isAutoGenerated && (
                <div className="mx-6 sm:mx-10 mt-6 p-4 bg-amber-50 border border-amber-200 rounded-xl text-xs space-y-2 text-slate-800">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 font-bold text-amber-900">
                      <Sparkles className="w-4 h-4 text-amber-600" />
                      <span>2-Hour Autonomous Global Research Engine (Gemini AI Dispatch)</span>
                    </div>
                    <span className="text-[10px] font-mono bg-amber-200/80 px-2 py-0.5 rounded text-amber-950 font-semibold">
                      Edition #{activeBlogPost.editionCycle}
                    </span>
                  </div>
                  {activeBlogPost.imagePrompt && (
                    <div className="text-[11px] text-slate-600 bg-white/70 p-2.5 rounded-lg border border-amber-100">
                      <span className="font-semibold text-slate-900">Featured Image Concept: </span>
                      {activeBlogPost.imagePrompt}
                    </div>
                  )}
                  {activeBlogPost.sources && activeBlogPost.sources.length > 0 && (
                    <div className="flex flex-wrap items-center gap-1.5 pt-1">
                      <span className="text-[11px] font-semibold text-slate-700">Verified Global Citations:</span>
                      {activeBlogPost.sources.map((src, idx) => (
                        <span key={idx} className="bg-white border border-slate-200 px-2 py-0.5 rounded text-[10px] text-slate-600">
                          {src}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Article Content */}
              <div className="p-6 sm:p-10 prose prose-slate max-w-none text-slate-800 leading-relaxed text-sm sm:text-base whitespace-pre-line font-serif">
                {activeBlogPost.content}
              </div>

              {/* Attached Media Gallery (Up to 10GB per article) */}
              {activeBlogPost.media && activeBlogPost.media.length > 0 && (
                <div className="mx-6 sm:mx-10 mb-8 p-5 bg-gradient-to-br from-slate-900 via-slate-800 to-[#131921] rounded-2xl text-white border border-amber-400/30 shadow-xl space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-700/80 pb-3">
                    <div className="flex items-center gap-2">
                      <HardDrive className="w-5 h-5 text-amber-400" />
                      <div>
                        <h4 className="font-serif font-bold text-sm text-amber-300">Attached Media & High-Capacity Master Files</h4>
                        <p className="text-[11px] text-slate-400">{activeBlogPost.media.length} media assets included with this article</p>
                      </div>
                    </div>
                    <span className="text-[10px] bg-amber-400/20 text-amber-300 border border-amber-400/30 px-2.5 py-0.5 rounded-full font-mono">
                      Cloud Stored (10GB Limit Supported)
                    </span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {activeBlogPost.media.map((file) => (
                      <div
                        key={file.id}
                        className="bg-slate-800/80 hover:bg-slate-800 border border-slate-700 rounded-xl p-3 flex flex-col justify-between space-y-2 transition"
                      >
                        <div className="flex items-start gap-3">
                          <div className="p-2.5 bg-slate-900 rounded-lg text-amber-400">
                            {file.category === 'video' && <Video className="w-4 h-4" />}
                            {file.category === 'audio' && <Music className="w-4 h-4" />}
                            {file.category === 'image' && <ImageIcon className="w-4 h-4" />}
                            {file.category === 'document' && <FileText className="w-4 h-4" />}
                            {file.category === 'archive' && <HardDrive className="w-4 h-4" />}
                          </div>
                          <div className="min-w-0 flex-1">
                            <p className="text-xs font-semibold text-white truncate" title={file.name}>
                              {file.name}
                            </p>
                            <p className="text-[10px] text-slate-400">
                              {(file.sizeBytes / (1024 * 1024)).toFixed(2)} MB • {file.mimeType}
                            </p>
                          </div>
                        </div>

                        {file.category === 'audio' && file.url && (
                          <audio controls className="w-full h-8 mt-1 rounded">
                            <source src={file.url} type={file.mimeType} />
                          </audio>
                        )}

                        {file.category === 'video' && file.url && (
                          <div className="rounded-lg overflow-hidden border border-slate-700 mt-1 max-h-48 bg-black">
                            <video controls className="w-full h-full object-contain">
                              <source src={file.url} type={file.mimeType} />
                            </video>
                          </div>
                        )}

                        {file.category === 'image' && file.url && (
                          <div className="rounded-lg overflow-hidden border border-slate-700 mt-1 max-h-40 bg-black">
                            <img src={file.url} alt={file.name} className="w-full h-full object-cover" />
                          </div>
                        )}

                        {file.url && (
                          <a
                            href={file.url}
                            download={file.name}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 text-[11px] text-amber-300 hover:text-amber-200 font-semibold pt-1"
                          >
                            <Download className="w-3 h-3" />
                            <span>Download / Stream Asset</span>
                          </a>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Article Tags */}
              <div className="px-6 sm:px-10 pb-6 flex flex-wrap gap-2">
                {activeBlogPost.tags.map((tag, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1 bg-slate-100 text-slate-700 text-xs px-3 py-1 rounded-full font-medium"
                  >
                    <Tag className="w-3 h-3 text-slate-400" />
                    {tag}
                  </span>
                ))}
              </div>

              {/* Comments Section */}
              <div className="bg-slate-50 p-6 sm:p-10 border-t border-slate-200 space-y-6">
                <div className="flex items-center justify-between">
                  <h3 className="font-bold text-sm sm:text-base text-slate-900 flex items-center gap-2">
                    <MessageSquare className="w-4 h-4 text-amber-500" />
                    <span>Discussion & Community Responses ({activeBlogPost.comments?.length || 0})</span>
                  </h3>
                </div>

                {/* New Comment Input */}
                <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm space-y-3">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    <input
                      type="text"
                      value={commentAuthor}
                      onChange={(e) => setCommentAuthor(e.target.value)}
                      placeholder="Your Name (Author, Reader, Visitor)"
                      className="text-xs bg-slate-50 border border-slate-300 rounded-lg p-2 text-slate-900 outline-none focus:border-amber-400"
                    />
                  </div>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={commentInput}
                      onChange={(e) => setCommentInput(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleAddComment(activeBlogPost.id)}
                      placeholder="Share your perspective on this article..."
                      className="flex-1 text-xs bg-slate-50 border border-slate-300 rounded-lg p-2.5 text-slate-900 outline-none focus:border-amber-400"
                    />
                    <button
                      onClick={() => handleAddComment(activeBlogPost.id)}
                      className="px-4 py-2 bg-amber-400 hover:bg-amber-500 text-slate-950 font-bold text-xs rounded-lg transition shadow flex items-center gap-1 cursor-pointer"
                    >
                      <Send className="w-3.5 h-3.5" />
                      <span>Post</span>
                    </button>
                  </div>

                  {/* AI Suggestions below comment form */}
                  <UniversalAiSuggestionBox
                    context="blog-comments"
                    label="AI Reader Perspective & Thoughtful Questions"
                    title={activeBlogPost.title}
                    onApply={(text) => setCommentInput(text)}
                    defaultExpanded={false}
                  />
                </div>

                {/* Comments List */}
                <div className="space-y-3">
                  {activeBlogPost.comments && activeBlogPost.comments.length > 0 ? (
                    activeBlogPost.comments.map((comment) => (
                      <div key={comment.id} className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm space-y-1">
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-xs text-slate-900">{comment.author}</span>
                          <span className="text-[11px] text-slate-400">{comment.date}</span>
                        </div>
                        <p className="text-xs text-slate-700 leading-relaxed">{comment.text}</p>
                      </div>
                    ))
                  ) : (
                    <p className="text-xs text-slate-500 italic">No comments yet. Start the dialogue!</p>
                  )}
                </div>
              </div>
            </article>
          </div>
        ) : (
          /* Article Directory / Grid View */
          <div className="space-y-6">
            {/* Search & Filter Bar */}
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-white p-3 rounded-xl border border-slate-200 shadow-sm">
              {/* Category Pills */}
              <div className="flex items-center gap-1.5 overflow-x-auto pb-1 sm:pb-0 scrollbar-none text-xs">
                {categories.map((cat) => (
                  <button
                    key={cat.id}
                    onClick={() => setSelectedCategory(cat.id)}
                    className={`px-3 py-1.5 rounded-lg whitespace-nowrap text-xs font-semibold transition cursor-pointer ${
                      selectedCategory === cat.id
                        ? 'bg-amber-400 text-slate-950 font-bold shadow-sm'
                        : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100'
                    }`}
                  >
                    {cat.label}
                  </button>
                ))}
              </div>

              {/* Search Box */}
              <div className="relative w-full sm:w-64 shrink-0">
                <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search articles & topics..."
                  className="w-full pl-9 pr-3 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-lg outline-none focus:border-amber-400"
                />
              </div>
            </div>

            {/* Articles Grid / Empty State */}
            {filteredPosts.length === 0 ? (
              <div className="bg-white rounded-2xl border border-dashed border-slate-300 p-12 text-center max-w-xl mx-auto space-y-4">
                <div className="w-14 h-14 mx-auto rounded-full bg-amber-50 flex items-center justify-center text-amber-500 border border-amber-200">
                  <PenSquare className="w-6 h-6" />
                </div>
                <div className="space-y-1">
                  <h3 className="font-serif font-bold text-lg text-slate-900">No Blog Articles Published Yet</h3>
                  <p className="text-xs text-slate-500 leading-relaxed max-w-md mx-auto">
                    Be the first author to publish an article! You can upload all sorts of media files up to 10GB and generate AI outlines and title suggestions directly within the dialog.
                  </p>
                </div>
                <button
                  onClick={() => setIsWritingModalOpen(true)}
                  className="inline-flex items-center gap-2 bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-500 hover:to-amber-600 text-slate-950 font-bold text-xs px-5 py-2.5 rounded-full shadow-md cursor-pointer transition"
                >
                  <Sparkles className="w-4 h-4 text-slate-950" />
                  <span>Write First Article with AI & 10GB Media</span>
                </button>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {filteredPosts.map((post) => (
                  <div
                    key={post.id}
                    onClick={() => setActiveBlogPost(post)}
                    className="bg-white rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition duration-200 overflow-hidden cursor-pointer flex flex-col group"
                  >
                    <div className="relative h-48 w-full overflow-hidden bg-slate-100">
                      <img
                        src={post.coverImage}
                        alt={post.title}
                        className="w-full h-full object-cover group-hover:scale-105 transition duration-300"
                      />
                      <div className="absolute top-3 left-3">
                        <span className="bg-[#131921]/90 backdrop-blur-md text-amber-300 text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-wider border border-amber-400/30">
                          {post.category}
                        </span>
                      </div>
                      {post.isAutoGenerated && (
                        <div className="absolute top-3 right-3">
                          <span className="bg-amber-400/95 backdrop-blur-md text-slate-950 text-[10px] font-extrabold px-2.5 py-1 rounded-full uppercase tracking-wider shadow-sm flex items-center gap-1">
                            <Sparkles className="w-3 h-3 text-slate-950" />
                            2-Hr AI Edition #{post.editionCycle}
                          </span>
                        </div>
                      )}
                    </div>

                    <div className="p-5 flex-1 flex flex-col justify-between space-y-3">
                      <div className="space-y-1.5">
                        <h3 className="font-serif font-bold text-base text-slate-900 group-hover:text-amber-600 transition line-clamp-2">
                          {post.title}
                        </h3>
                        <p className="text-xs text-slate-600 line-clamp-2 leading-relaxed">
                          {post.subtitle || post.excerpt}
                        </p>
                      </div>

                      <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
                        <div className="flex items-center gap-2">
                          <img
                            src={post.authorAvatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80'}
                            alt={post.author}
                            className="w-6 h-6 rounded-full object-cover"
                          />
                          <span className="font-semibold text-slate-800 text-[11px] truncate max-w-[120px]">
                            {post.author}
                          </span>
                        </div>

                        <div className="flex items-center gap-3 text-[11px]">
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3 text-slate-400" />
                            {post.readTimeMinutes} min
                          </span>
                          <span className="flex items-center gap-1 text-rose-600 font-semibold">
                            <Heart className="w-3 h-3 fill-rose-500" />
                            {post.likesCount}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Copy Toast */}
      {copiedToast && (
        <div className="fixed bottom-6 z-50 left-1/2 -translate-x-1/2 bg-slate-900 text-amber-300 font-bold text-xs px-5 py-2.5 rounded-full shadow-2xl flex items-center gap-2 animate-in fade-in slide-in-from-bottom duration-200 border border-amber-400/40">
          <Check className="w-4 h-4 text-emerald-400" />
          <span>Article URL copied to clipboard! Ready to share on WhatsApp or Twitter.</span>
        </div>
      )}

      {/* Write Article Modal */}
      {isWritingModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
          <div className="w-full max-w-4xl bg-white rounded-3xl shadow-2xl p-6 sm:p-8 text-xs text-slate-900 space-y-6 my-6 max-h-[92vh] overflow-y-auto">
            <div className="flex items-center justify-between pb-4 border-b border-slate-200">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-600">
                  <PenSquare className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-lg text-slate-900 font-serif">Write & Publish an Article</h3>
                  <p className="text-[11px] text-slate-500">
                    Includes AI Content Outline & Suggestions, 10GB Media Upload, and automated Schema.org Google metadata
                  </p>
                </div>
              </div>
              <button
                onClick={() => setIsWritingModalOpen(false)}
                className="text-slate-400 hover:text-slate-700 p-1.5 rounded-lg hover:bg-slate-100 transition cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* AI Assistant Section */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-amber-500" />
                  <span className="font-bold text-xs text-slate-800">AI Assistant & Writing Suggestions</span>
                </div>
                <button
                  type="button"
                  onClick={() => setShowAiAssistant(!showAiAssistant)}
                  className="text-[11px] text-amber-600 hover:text-amber-700 font-semibold cursor-pointer"
                >
                  {showAiAssistant ? 'Hide AI Suggestions' : 'Show AI Suggestions'}
                </button>
              </div>

              {showAiAssistant && (
                <BlogAiSuggestionsPanel
                  currentTitle={newTitle}
                  currentCategory={newCategory}
                  onApplyOutline={(outline) => {
                    setNewContent((prev) => (prev ? `${prev}\n\n${outline}` : outline));
                  }}
                  onApplyTitle={(title) => {
                    setNewTitle(title);
                  }}
                  onApplySubtitle={(subtitle) => {
                    setNewSubtitle(subtitle);
                  }}
                  onApplyTags={(tags) => {
                    setNewTags((prev) => {
                      const combined = Array.from(new Set([...prev.split(',').map(s => s.trim()).filter(Boolean), ...tags]));
                      return combined.join(', ');
                    });
                  }}
                  onApplyCategory={(category) => {
                    setNewCategory(category);
                  }}
                  onApplyMarkdown={(markdown) => {
                    setNewContent((prev) => (prev ? `${prev}\n\n${markdown}` : markdown));
                  }}
                />
              )}
            </div>

            <form onSubmit={handleCreateArticle} className="space-y-5 pt-2">
              <div>
                <label className="block font-bold text-slate-800 mb-1.5">
                  Article Title <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. The Architecture of E-Paper: Why Distraction-Free Hardware Endures"
                  className="w-full border border-slate-300 rounded-xl p-3 text-xs sm:text-sm text-slate-900 outline-none focus:border-amber-400 focus:ring-2 focus:ring-amber-400/20 font-serif font-bold"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-800 mb-1.5">
                  Subtitle / Teaser
                </label>
                <input
                  type="text"
                  value={newSubtitle}
                  onChange={(e) => setNewSubtitle(e.target.value)}
                  placeholder="A one-sentence summary for search engine previews & social cards"
                  className="w-full border border-slate-300 rounded-xl p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                  <label className="block font-bold text-slate-800 mb-1">Your Name</label>
                  <input
                    type="text"
                    required
                    value={newAuthor}
                    onChange={(e) => setNewAuthor(e.target.value)}
                    className="w-full border border-slate-300 rounded-lg p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-800 mb-1">Your Role</label>
                  <select
                    value={newAuthorRole}
                    onChange={(e) => setNewAuthorRole(e.target.value as any)}
                    className="w-full border border-slate-300 rounded-lg p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400 bg-white"
                  >
                    <option value="Author">Author</option>
                    <option value="Reader">Reader</option>
                    <option value="Literary Scholar">Literary Scholar</option>
                    <option value="Books Critic">Books Critic</option>
                    <option value="Visitor">Visitor</option>
                  </select>
                </div>
                <div>
                  <label className="block font-bold text-slate-800 mb-1">Category</label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value)}
                    className="w-full border border-slate-300 rounded-lg p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400 bg-white"
                  >
                    <option value="10 Dimensions & Hardware">10 Dimensions & Hardware</option>
                    <option value="Craft & Writing">Craft & Writing</option>
                    <option value="Publishing Industry">Publishing Industry</option>
                    <option value="Philosophy & Literature">Philosophy & Literature</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block font-bold text-slate-800">Cover Image URL</label>
                    <div className="flex items-center gap-1.5">
                      <input
                        type="file"
                        ref={coverCameraInputRef}
                        accept="image/*"
                        capture="environment"
                        className="hidden"
                        onChange={(e) => {
                          const f = e.target.files?.[0];
                          if (f) setNewCoverImage(URL.createObjectURL(f));
                        }}
                      />
                      <button
                        type="button"
                        onClick={() => coverCameraInputRef.current?.click()}
                        className="text-[11px] text-amber-700 hover:text-amber-900 font-semibold flex items-center gap-1 cursor-pointer"
                        title="Take cover photo with phone camera"
                      >
                        <Smartphone className="w-3 h-3 text-amber-600" />
                        <span>Phone</span>
                      </button>
                      <span className="text-slate-300">•</span>
                      <button
                        type="button"
                        onClick={() => setIsCoverCameraOpen(true)}
                        className="text-[11px] text-amber-700 hover:text-amber-900 font-semibold flex items-center gap-1 cursor-pointer"
                      >
                        <Camera className="w-3 h-3 text-amber-600" />
                        <span>Live Snap</span>
                      </button>
                    </div>
                  </div>
                  <input
                    type="text"
                    value={newCoverImage}
                    onChange={(e) => setNewCoverImage(e.target.value)}
                    className="w-full border border-slate-300 rounded-lg p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-800 mb-1">Tags (comma-separated)</label>
                  <input
                    type="text"
                    value={newTags}
                    onChange={(e) => setNewTags(e.target.value)}
                    placeholder="e.g. 10 Dimensions, Silk, Archival Ink, E-Paper"
                    className="w-full border border-slate-300 rounded-lg p-2.5 text-xs text-slate-900 outline-none focus:border-amber-400"
                  />
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-800 mb-1.5">
                  Article Body & Content <span className="text-red-500">*</span>
                </label>
                <textarea
                  required
                  rows={9}
                  value={newContent}
                  onChange={(e) => setNewContent(e.target.value)}
                  placeholder="Draft your essay, book critique, manuscript reflection, or reading journal entry..."
                  className="w-full border border-slate-300 rounded-xl p-3.5 text-xs sm:text-sm text-slate-900 outline-none focus:border-amber-400 font-serif leading-relaxed"
                />
              </div>

              {/* AI Suggestion Box below Article Form */}
              <UniversalAiSuggestionBox
                context="blog-editor"
                title={newTitle}
                category={newCategory}
                label="AI Editorial Assistant: Headings, Hooks & 10-Dimension Reflections"
                onApply={(text) => {
                  setNewContent((prev) => (prev ? `${prev}\n\n${text}` : text));
                }}
              />

              {/* 10GB Media Upload Section */}
              <div className="border-t border-slate-200 pt-4">
                <BlogMediaUpload
                  mediaItems={mediaItems}
                  onMediaItemsChange={setMediaItems}
                />
              </div>

              <div className="pt-3 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200">
                <span className="text-[11px] text-emerald-600 font-semibold flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4" />
                  Auto-generates Google Schema.org metadata & OpenGraph preview
                </span>
                <div className="flex gap-2.5">
                  <button
                    type="button"
                    onClick={() => setIsWritingModalOpen(false)}
                    className="px-5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl cursor-pointer transition"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-7 py-2.5 bg-gradient-to-r from-amber-400 via-amber-500 to-amber-600 hover:from-amber-500 hover:to-amber-700 text-slate-950 font-bold rounded-xl shadow-lg cursor-pointer flex items-center gap-2 transition"
                  >
                    <PenSquare className="w-4 h-4" />
                    <span>Publish Article</span>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Native Camera Capture for Article Cover */}
      <NativeCameraCaptureModal
        isOpen={isCoverCameraOpen}
        onClose={() => setIsCoverCameraOpen(false)}
        title="Snap Article Cover Photo"
        defaultMode="photo"
        onCapture={(file) => {
          setNewCoverImage(URL.createObjectURL(file));
        }}
      />
    </div>
  );
};
